language: node_js
node_js:
  - "8.9.4"
install:
  - bash ./scripts/travis-install
script:
  - ganache-cli -p 7545 > /dev/null &
  - sleep 5
  - ava test/create.js
cache:
  directories:
    - "node_modules"
