#!/bin/bash

# lint
npm run lint

# run local truffle node
ganache-cli &
sleep 5

# ara node_modules/.bin to PATH
PATH=$(npm bin):$PATH

# move deploy identity to home dir
mkdir -p ~/.ara/identities
cp test/fixtures/identities ~/.ara/identities
echo "identities directory $(ls ~/.ara/identities)"

cd node_modules/ara-contracts
truffle migrate --network local

DEBUG=ara* act deploy -S -d 8a98c8305035dcbb1e8fa0826965200269e232e45ac572d26a45db9581986e67 -f -p pass \
-v 1 ./contracts/AFS.sol ./contracts/Library.sol ./contracts/Registry.sol ./contracts/Proxy.sol ./contracts/AraToken.sol &

# deploy process doesn't close on its own, must sleep
sleep 15

cd ../..

ava test/create.js --verbose
ava test/add.js --verbose
ava test/remove.js --verbose
ava test/unarchive.js --verbose
ava test/key-path.js --verbose
ava test/metadata.js --verbose
ava test/util.js --verbose
ava test/storage.js --verbose
ava test/destroy.js --verbose
ava test/commit.js --verbose
ava test/price.js --verbose

# TODO: aid.js

# cleanup
pkill -f ganache 
