#!/bin/bash

safeRunCommand() {
  typeset cmnd="$*"
  typeset ret_code

  echo cmnd=$cmnd
  eval $cmnd

  ret_code=$?
  if [ $ret_code != 0 ]; then
    printf "Error : [%d] when executing command: '$cmnd'" $ret_code
    exit $ret_code
  fi
}

# run local truffle node
ganache-cli -l 0x7A1200 &
sleep 5

# ara node_modules/.bin to PATH
PATH=$(npm bin):$PATH

# move deploy identity to home dir
mkdir -p ~/.ara/identities/
chmod +r ~/.ara/identities/
cp -a test/fixtures/identities/. ~/.ara/identities/

cd node_modules/ara-contracts
truffle migrate --network local

# deploy process doesn't close on its own, must sleep
sleep 20

cd ../..


command="ava test/add.js --verbose"
safeRunCommand "$command"

command="ava test/commit.js --verbose"
safeRunCommand "$command"

command="ava test/create.js --verbose"
safeRunCommand "$command"

command="ava test/deploy.js --verbose"
safeRunCommand "$command"

command="ava test/destroy.js --verbose"
safeRunCommand "$command"

command="ava test/key-path.js --verbose"
safeRunCommand "$command"

command="ava test/metadata.js --verbose"
safeRunCommand "$command"

command="ava test/price.js --verbose"
safeRunCommand "$command"

command="ava test/remove.js --verbose"
safeRunCommand "$command"

command="ava test/storage.js --verbose"
safeRunCommand "$command"

command="ava test/unarchive.js --verbose"
safeRunCommand "$command"

command="ava test/util.js --verbose"
safeRunCommand "$command" safeRunCommand "$command"

# cleanup
pkill -f ganache
