#!/bin/bash

# lint and ava
npm run lint
#npm run test --verbose
ava test/create.js
ava test/add.js
ava test/remove.js
ava test/unarchive.js
ava test/key-path.js
ava test/metadata.js
ava test/util.js
ava test/storage.js
